### ISSUE TITLE
Find-file that doesn't exist doesn't display confirmation dialog

### ISSUE THREAD

**Issue by rneatherway** [gempesaw/ido-vertical-mode.el#14]
However, pressing Enter a second time does create the buffer. I'm using a config like Magnar Sveen's:

```
(require 'ido)
(ido-mode t)
(setq ido-enable-prefix nil
      ido-enable-flex-matching t
      ido-case-fold nil
      ido-auto-merge-work-directories-length -1
      ido-create-new-buffer 'always
      ido-use-filename-at-point nil
      ido-max-prospects 10)

;; Try out flx-ido for better flex matching between words
(require 'flx-ido)
(flx-ido-mode 1)
;; disable ido faces to see flx highlights.
(setq ido-use-faces nil)

;; flx-ido looks better with ido-vertical-mode
(require 'ido-vertical-mode)
(ido-vertical-mode)
```

**Comment by gempesaw** [comment]
thanks! :)

**Comment by vmfhrmfoaj** [comment]
My English is poor, but I hope you can understand me.
and [My ido settings] (https://github.com/vmfhrmfoaj/.emacs.d/blob/master/configs/200-ido.el).

---

I was encountered a error as the following:
> Error in post-command-hook (ido-exhibit): (wrong-type-argument characterp #(".ido.last" 1 4 (face flx-highlight-face)))

Reproduce:
- C-x C-f (`ido-find-file`)
- "ido" (typing some string)
- M-s (`ido-merge-work-directories`)

---

Error is caused by a code such as the following(4ec512c):
```elisp
;; ido-vertical-mode.el:96:
(mapconcat #'append comps "")
```

When error occurred, 
`comps(ido-matches)` is the list of string of candidates and path as the following:
```elisp
((#(".ido.last" 1 4 (face flx-highlight-face)) "/Users/JS/")
 (#("200-ido.el" 4 7 (face flx-highlight-face)) "/Users/JS/.emacs.d/configs/" "~/.emacs.d/configs/")
 ...)

;; So, (mapconcat #'append comps "") =>
(mapconcat #'append
           '((#(".ido.last" 1 4 (face flx-highlight-face)) "/Users/JS/")
             (#("200-ido.el" 4 7 (face flx-highlight-face)) "/Users/JS/.emacs.d/configs/" "~/.emacs.d/configs/"))
           "")
;; => Debugger entered--Lisp error: (wrong-type-argument characterp #(".ido.last" 1 4 (face flx-highlight-face)))
```

---

I've fixed the error, temporarily:
```elisp
(mapconcat #'(lambda (it)
               (append (if (listp it)
                           (car it)
                         it)))
           comps
           "")
```

**Comment by gempesaw** [comment]
Ah, thanks for the information. I sort of expected that would probably break. Very helpful comment! :)

**Comment by gempesaw** [comment]
@vmfhrmfoaj hey, I pushed a fix that should address your issue. Let me know if you have any further problems. Thanks again for investigating what the problem was! :D

**Comment by vmfhrmfoaj** [comment]
Thanks :-)
