### ISSUE TITLE
Allow "fixed" files list with up/down moving selection

### ISSUE THREAD

**Issue by Silex** [gempesaw/ido-vertical-mode.el#19]
Hello,

How hard would it be to implement a "fixed" files list where up/down moves the selection, instead of  the current behavior that scrolls the whole list in order to have the selection always at the same place?

Here are examples of what I mean (found these on the web so focus on the "selection" part):

![example1](https://camo.githubusercontent.com/3c58da05b4e3ccf2f717007c4d1c0bee415d670d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622d63736578746f6e2f756e6974652d30312e676966)

![example2](
https://camo.githubusercontent.com/51729e91b2aa7378bc54b7a8ce8ec597584a6ae1/687474703a2f2f692e696d6775722e636f6d2f6e3345776556332e706e67)

There's already some implementation to be inspired from in `fiplr` (or  `helm`?).

Before you ask "what happens if you scroll down past the last item", then the behavior should be "the entire lists scrolls". Basically like a combobox (select box) behaves in HTML:

http://jsfiddle.net/o30akd0r/

(Just click on the select box and press up/down to see)

**Comment by gempesaw** [comment]
Hm, it's possibly not too complicated, although I'm not positive. There's not actually that much going on in this package, unless I miss my mark. `ido-mode` lets you customize the separators between elements, as well as the indicator, first item, and last item. By default, the separators are `|` and the first/last are `{ }`; changing the separators to `"\n"` is probably the biggest deal. 

I'm not sure if the minibuffer would refresh immediately from changes to the `ido-decorations` variable. If it does, we could get a little clever about tracking which one of the ido candidates we're selecting, and rotate the decorations properly whenever the user navigates the list. maybe we advise `ido-next|prev-match` to know when to update the decorations ? I hope there'd be a cleaner way than advise though...

okay i just checked and toggling `ido-vertical-mode` while I've got an open `ido-find-file` going on does toggle the display from inline to newline separated, so yeah that's probably completely impossible.

**Comment by Silex** [comment]
@gempesaw: thanks for the feedback.

I'm not sure I follow how to implement this tho... Unless I'm missing something, I don't see a way to render "the 4th item in the list" in a different face with `ido-decorations`. 

I gave it some thought, and I think it'd be possible to modify the text properties of the completion results, for example like how `flx-ido-decorate` does. The implementation would then become something like:

* when `up/down` is pressed, render the same list of completions with text properties updated.
* when `enter` is pressed (a completion is selected), make sure to select the correct one (e.g *not* the one at the top).

Do you agree?

**Comment by gempesaw** [comment]
Ooh, good points, I didn't think of any of those items. But all those make sense, yeah.

**Comment by Silex** [comment]
Alright, I'll see if I can hack something :) as you know your way around ido, can you maybe point obvious variables/functions to play with? e.g where the completions are stored, which hook is called to render the completions etc.

If you don't know or don't have time, I'll look it up myself but it never hurt to ask :)

**Comment by gempesaw** [comment]
```elisp
                  (alternatives
                   (apply
                    #'concat
                    (cdr (apply
                          #'nconc
                          (mapcar
                           (lambda (com)
                             (setq com (ido-name com))
                             (setq items (1- items))
                             (cond
                              ((< items 0) ())
                              ((= items 0) (list additional-items-indicator)) ; " | ..."
                              (t
                               (list (nth 2 ido-decorations) ; " | "
                                     (let ((str (substring com 0)))
                                       (if (and ido-use-faces
                                                (not (string= str first))
                                                (ido-final-slash str))
                                           (put-text-property 0 (length str) 'face 'ido-subdir str))
                                       str)))))
                           comps)))))
```

Looks like that builds the completion string and later on

```elisp
              ;; list all alternatives
              (nth 0 ido-decorations) ;; { ... }
              alternatives
              (nth 1 ido-decorations)
```

puts the whole string together for output. hth !
