### ISSUE TITLE
Still using ido-vertical-match-face although ido-use-faces is nil

### ISSUE THREAD

**Issue by joca-bt** [gempesaw/ido-vertical-mode.el#23]
The new faces functionality introduced an error (commit 66b105a7cfa8c2f95945dd5ffd2eb5d8f4f56a76). Highlighting by ```ido-vertical-match-face``` is still being done even if ```(setq ido-use-faces nil)```. This is particularly bothersome if you are using ```flx-ido```.

On the other hand, ```ido-vertical-show-count``` is only being shown when ```ido-use-faces``` is true. I don't think it has anything to do with faces, and so it shouldn't be tied to ```ido-use-faces``` in my opinion. This would allow us to have the count even when not using any faces.

**Comment by gempesaw** [comment]
hmm, thanks for the heads up. i'll move those around.

**Comment by gempesaw** [comment]
those should both be fixed in master. thanks for the help!

coincidentally, how are you getting your packages updated so frequently?

**Comment by joca-bt** [comment]
Thanks for the fixes! I'm using MELPA.
