### ISSUE TITLE
match returned with text properties

### ISSUE THREAD

**Issue by milanst** [gempesaw/ido-vertical-mode.el#26]
Sometimes the string that ido-vertical returns to calling functions contains text properties that then end up in buffer-file-name variable.

In one of those cases running C-h v buffer-file-name gives me:
buffer-file-name is a variable defined in `C source code'.
Its value is #("foo.ml" 56 58 (face ido-vertical-match-face))

This causes issues with merlin mode (mode for OCaml programming) which sends the value of buffer-file-name over the wire to its external process. I'll fix the issue in merlin, but I think ido-vertical should drop the text properties before passing the match to calling functions. There are other weird artifacts. For example, the name of the buffer in the list of buffers contains two characters in yellow (the characters I typed in during ido-find-file).

I can't reliably reproduce this. You definitely need to type a couple of characters (to force the parts of filenames to be highlighted) but then selecting a file (by pressing enter) doesn't always lead to this undesirable behavior. 

I use ido-ubiquitous-mode in combination with ido-vertical if it matters but I'm pretty sure it is the issue with ido-vertical since it started happening only after I upgraded ido-vertical couple of weeks ago.

**Comment by gempesaw** [comment]
Ah, hmm. I ran into this issue with the PR I merged at that time, but I thought I fixed it and added a test to catch it. 

Well, I'll take another look. Thanks for the heads up!

**Comment by milanst** [comment]
I'm using version 20150215.913 from melpa if it helps.
